language: php

sudo: true

matrix:
  include:
    - php: 7.3
      env: LARAVEL_VERSION=7.*
    - php: 7.4
      env: LARAVEL_VERSION=8.*
    - php: 8.0
      env: LARAVEL_VERSION=8.*

before_install:
  - composer self-update --stable -n
  - composer update

install:
  - travis_retry composer install --no-suggest

script:
  - vendor/bin/phpunit --coverage-clover clover.xml;

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar;
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml;
  - bash <(curl -s https://codecov.io/bash)
