language: php

sudo: true

matrix:
  include:
    - php: 7.0
      env: LARAVEL_VERSION=5.1.*
    - php: 7.1
      env: LARAVEL_VERSION=5.3.*
    - php: 7.1
      env: LARAVEL_VERSION=5.5.*
    - php: 7.1
      env: LARAVEL_VERSION=5.6.*
    - php: 7.2
	  env: LARAVEL_VERSION=5.7.*

before_install:
  - composer self-update --stable -n

install:
  - travis_retry composer install --no-suggest

script:
  - vendor/bin/phpunit --coverage-clover clover.xml;

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar;
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml;
  - bash <(curl -s https://codecov.io/bash)